run:
	xfce4-terminal -e "python3 Assignment/mana.py"
	xfce4-terminal -e "python3 Assignment/envi.py"
	xfce4-terminal -e "python3 Assignment/temp.py"
	xfce4-terminal -e "python3 Assignment/humi.py"
	xfce4-terminal -e "python3 Assignment/co2l.py"
	xfce4-terminal -e "python3 Assignment/heat.py"
	xfce4-terminal -e "python3 Assignment/cool.py"
	xfce4-terminal -e "python3 Assignment/wate.py"
	xfce4-terminal -e "python3 Assignment/co2i.py"
	xfce4-terminal -e "python3 Assignment/clie.py"
